### ISSUE TITLE
Lazy Loading of GRF files

### ISSUE THREAD

**Issue by arminherling** [arminherling/GRF#1]
All entries of GRF files are currently loaded into memory, this can easily become an problem on 32bit systems.
Loading the whole GRF file upfront is potentially faster when the user wants to extract a lot of entries.
The user should be able to decide if they want to load the whole GRF file upfront or lazy load each entry on access.
Lazy loading should be the default mode.

**Comment by carloshenrq** [comment]
I Think we can use that way:

When we open the grf, we need basic only 'name, start offset, lenght'.
As i see in your code, you're reading all files and putting it on memory and as you say this way is lazy.

We can change this:

```
Entries.Add(
    fileName,
    new GrfEntry(
        streamReader.ReadBytes( compressedFileSizeAligned ),
        fileName,
        compressedFileSize,
        uncompressedFileSize,
        fileFlags ) );
```

To something like:

```
Entries.Add(
    fileName,
    new GrfEntry(
    	fileName,
    	fileEntryHeader,
    	compressedFileSize,
    	compressedFileSizeAligned,
        fileFlags ) );
```

This way, only the file position is stored in memory. Huge files won't be a problem.

And, for reading the file, when it's need, change this:

```
public byte[] GetUncompressedData()
{
    Span<byte> newData = stackalloc byte[CompressedSizeAligned];
    _data.CopyTo( newData );

    if( Flags.HasFlag( FileFlag.Mixed ) )
    {
        DecodeFull( newData, CompressedSize );
    }
    else if( Flags.HasFlag( FileFlag.DES ) )
    {
        DecodeHeader( newData );
    }
    return ZlibStream.UncompressBuffer( newData.ToArray() );
}
```


To something like:
```
public byte[] GetUncompressedData()
{
    Span<byte> newData = stackalloc byte[CompressedSizeAligned];
    _grfOwner.streamReader.BaseStream.Seek(fileEntryHeader, SeekOrigin.Begin);
    _grfOwner.streamReader.ReadBytes(CompressedSizeAligned).CopyTo(newData);

    if( Flags.HasFlag( FileFlag.Mixed ) )
    {
        DecodeFull( newData, CompressedSize );
    }
    else if( Flags.HasFlag( FileFlag.DES ) )
    {
        DecodeHeader( newData );
    }
    return ZlibStream.UncompressBuffer( newData.ToArray() );
}
```

**Comment by carloshenrq** [comment]
This'll get more lazy for extract but this still worth it for both cases

**Comment by arminherling** [comment]
Hello,
I opened this issue just so I don't forget about this but thanks for your comment :smiley: 

Yes your idea is good, what I meant was this: [Lazy Loading](https://en.wikipedia.org/wiki/Lazy_loading)
Just loading the entry names is already around 2GB in a normal RO client, this is a problem on 32bit systems, thats why I don't want to create lots of GrfEntry in GRF.Load().

My current plan is to check the file table inside the grf when the user calls Grf.Entry[] or GrfCollection.TryFind() and lookup the position of the entry data, then uncompress it and return a new GrfEntry to the user. This can easily be cached, not sure yet if a cache is needed tho.

I still need to decide if I want to create an IGrf interface and implement this in a second class  and keep the current Grf class or if I replace the current one. A second class would give the user the option to load all into memory or just load the wanted entries. I'll decide this after benchmarking the new implementation.

**Comment by carloshenrq** [comment]
@arminherling I understand better what you say now.
For faster search, hash table isn't good? Or you wanna use other methods like in SQL we can use "column1 LIKE 'text%'?

If it's a direct search, hash table should solve this problem.

This code (https://github.com/MagicalTux/grf/blob/master/src/grf.c#L913-L962) uses hash table for entries...

**Comment by arminherling** [comment]
Oh good idea, I will try that out when I got time :+1:
